package httpapi

import (
	"net/http"

	"github.com/M-Arthur/order-food-api/internal/bootstrap"
	"github.com/M-Arthur/order-food-api/internal/httpapi/handlers"
	"github.com/M-Arthur/order-food-api/internal/httpapi/middleware"
	"github.com/go-chi/chi/v5"
	chimiddleware "github.com/go-chi/chi/v5/middleware"
	"github.com/rs/zerolog"

	_ "github.com/M-Arthur/order-food-api/docs" // generated docs
	httpSwagger "github.com/swaggo/http-swagger"
)

// RouterConfig centralises configuration for the router
type RouterConfig struct {
	Logger zerolog.Logger
	Deps   *bootstrap.Dependencies
	APIKey string
}

// NewRouter builds the HTTP router with middleware and routes
func NewRouter(cfg RouterConfig) http.Handler {
	r := chi.NewRouter()

	// Swagger UI route
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// Serve generated swagger.json (if present) as static file
	r.Get("/swagger/doc.json", func(w http.ResponseWriter, r *http.Request) {
		// Serve the JSON file generated by swag into ./docs/swagger.json
		http.ServeFile(w, r, "./docs/swagger.json")
	})

	// --- Route groups / endpoints ---
	r.Get("/health", handlers.Health)

	r.Route("/api", func(api chi.Router) {
		// --- Middlewares ---
		api.Use(
			chimiddleware.StripSlashes,
			chimiddleware.RequestID,
			chimiddleware.RealIP,
			middleware.LoggerMiddleware(cfg.Logger),
			middleware.Recover,
			middleware.JSONContentType,
			middleware.RequestLogger,
		)
		// swagger:route GET /product product listProducts
		api.Get("/product", cfg.Deps.Handlers.Product.ListProducts)
		// swagger:route GET /product/{productId} product getProduct
		api.Get("/product/{productId}", cfg.Deps.Handlers.Product.GetProductByID)
		// swagger:route POST /order order placeOrder
		api.With(middleware.APIKeyAuth(cfg.APIKey)).Post("/order", cfg.Deps.Handlers.Order.PlaceOrder)
	})

	// Serve Swagger UI at /swagger/*, pointing to /swagger/doc.json
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))

	return r
}
